name: Rebuild
on:
  workflow_dispatch:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  rebuild:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Node
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 24
      - name: Setup Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: 3.12
      - name: Setup Java
        uses: actions/setup-java@v5.0.0
        with:
          distribution: 'temurin'
          java-version: 17
          java-package: 'jre'
          
      - name: Checkout
        uses: actions/checkout@v6-beta
      
      - name: Rebuild
        run: |
         npm install
         npm run translate
       
      - name: Upload built-dist
        uses: actions/upload-artifact@v5.0.0
        with:
          name: built-dist
          path: dist
      - name: Upload built-media
        uses: actions/upload-artifact@v5.0.0
        with:
          name: built-media
          path: media
          
      - name: Checkout to develop-builds
        uses: actions/checkout@v6-beta
        with:
          ref: develop-builds
      
      - name: Clear out things
        run: |
          rm -rf dist/*
          rm -rf media/*
          
      - name: Download built-dist
        uses: actions/download-artifact@v6.0.0
        with:
          name: built-dist
          path: dist/
      - name: Download built-media
        uses: actions/download-artifact@v6.0.0
        with:
          name: built-media
          path: media/
      
      - name: Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: ${{ github.event.head_commit.message }}
          committer_name: GitHub Actions
          committer_email: actions@github.com
